### PR TITLE
Added Date Created for Animals

### PR DESCRIPTION
**Pull request by stevenbertolucci**
Added a Date Created field to animal cards, filter, and database. 

Animals that were added prior to this pull request had to have the 'date created' field added manually in Firestore database. With this new functionality that I implemented, all new animals will have the date automatically added when users clicks on "Add Animal." 

Date Created also shows up in the filter menu and currently works. Will implement an improved filter menu to sort animals from oldest first or newest first instead of listing every date created for all the animals.

### CODE REVIEW

**Comment by TeresitaCGNader** [comment]
Hi Steven,

That's a great start, and now we can see the date. However, I think the current filter setup is becoming a bit too lengthy. Could we try a different approach for the date filtering? I found this example on CodeSandbox that might offer a more streamlined solution: [React Table Filter by Date Range](https://codesandbox.io/p/sandbox/react-table-filter-by-date-range-5mm07g). It seems like it could be a more efficient way to handle date ranges. Let me know what you think!

Best,
Teresita Nader

**Comment by stevenbertolucci** [comment]
Hi Teresita, 

I do agree that it is getting lengthy and one of the suggestions that I mentioned is to get rid of the "filter by date created" and move it to a sort menu. That way users can sort the animals from either selecting "newest first" or "oldest first." Should I implement this as well? 

Regarding your date range, that sounds like a great idea! I can also implement that as well and it does seem more efficient as it allows users to pinpoint the animals from that certain date range with accuracy. Please let know if I should do both. 

Thanks!

**Comment by TeresitaCGNader** [comment]
Your solution of "newest first" or "oldest first" makes more sense. Can you apply that filter instead? Once that is complete I can approve your code.

**Comment by stevenbertolucci** [comment]
Fixed some bugs and implemented sort option for "Newest First", "Oldest First", and "Default". The code works great! 

Plus, I tweaked the search bar a little bit because when I was testing, I noticed that the search bar wasn't responsive on mobile phones. The old code had the search bar cut off and hard to see. The new code gives the search bar a modern look, and it is responsive on all platforms. Users can now see the search bar on any devices, filter animals, and sort animals by selecting "Newest First", "Oldest First", or "Default".

**Review by TeresitaCGNader — APPROVED** [review]
Loving the improvements! And the interface for the sort option looks amazing! For the next version can you use green colors? Our header, footer, and buttons all have green, you can grab them and see how those green tones look or use other green tones. Great work!

image

**Comment by stevenbertolucci** [comment]
That would be awesome! I can implement that for the next version for sure!

**Pull request merged**
