### PR TITLE
Pets Page can now Filter

### PR DESCRIPTION
**Pull request by stevenbertolucci**
Hi Team, 

I have pushed the code that displays the filter options: 'Type', 'Breed', 'Age', 'Gender', and 'Availability'. 

I have not yet implemented the code to filter animals by 'Creation Date'. Will start this on Tuesday. 

There are some bugs in the code that does not display the search result until the user completely deletes the search text. For instance, if I typed in 'Dog' and then hit enter, nothing changes. The animal cards will still display all animals. But, when I delete the text completely, only the dogs will now be displayed. The same can be done with other types of animals. I will attempt to fix this bug on Tuesday as well. 

On the other hand, the filter functionality works, but it is not at 100%. The filtering only works if users has already entered something in the search text box. Once the text has been entered, then the filters will work. If you attempt to filter without entering any text, then nothing will be filtered out regardless if the check boxes are selected. 

While these bugs are minor, the pets page will work but there will be extra steps to get the code to fully work as intended. I will attempt to fix those pesky bugs on Tuesday. I am pushing this code because it is required for the v0.3 assignment to show that I am making progress with my task. 

Feel free to leave any feedback.

### CODE REVIEW

**Comment by TeresitaCGNader** [comment]
The filters are not working for me, and there are several issues with how the cards are displayed, please fix this issues before merging your code to main.
screenshot

**Comment by cdgco** [comment]
I just pulled in the outdated changes, so the preview should now be accurate regarding the cards not displaying properly. @TeresitaCGNader

**Comment by stevenbertolucci** [comment]
Everything is working as intended. Please review this pull request. Thanks!

**Review by TeresitaCGNader — CHANGES_REQUESTED** [review]
Before merging can you change the availability filter to say "available" and "pending" instead of "yes" and "no"?

image

**Comment by stevenbertolucci** [comment]
Yes, for sure. I will make the change when I get home shortly.

**Comment by stevenbertolucci** [comment]
Changed 'No' in the filter menu to 'pending'. All tests passed.

**Comment by TeresitaCGNader** [comment]
Thanks!

**Review by TeresitaCGNader — APPROVED** [review]

**Pull request merged**
