### PR TITLE
Added Email for Signup

### PR DESCRIPTION
**Pull request by TinTinTheGuy**
What this does is it will send a Welcome Email to user whenever they signup for a new account following their email address.  The template of email currently just for show.

### CODE REVIEW

**Review by stevenbertolucci — COMMENTED** [review]
Awesome job! I tested it out and I did get an email notification from the website. The only issue is that I can't log in after hitting 'Sign Up', but I did get an email notification though. 

I also checked with the database and my user profile did not get added. As of right now, I can only create a shelter profile and log in using my shelter credentials. Please let me know if users couldn't create an account prior to this pull request and I'll approve it. I couldn't remember if users were able to create an account.

**Comment by TinTinTheGuy** [comment]
I will take a look at this soon, last time I check it out, only the Shelter will not receive the emails since I have not added to it.

**Comment by TinTinTheGuy** [comment]
@stevenbertolucci So I check the sign up, currently it only work with user signup only since I havent added to the shelter signup. If your email already in the database, under Authentication in firebase, it won't let you signup, but still get the email. The database still receive the information if you signup successfully with a different email not in the Authentication.

**Comment by stevenbertolucci** [comment]
Hi Tan, 

I tried to create an account using an email (under Adopt) that wasn't in the database and it still wouldn't let me create an account. I got an email confirmation though. Is it supposed to create an account once I click on 'Create Account"?

**Review by stevenbertolucci — APPROVED** [review]
Good job! Approving it.

**Pull request merged**
